config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "work_spaces#index"

  resources :users, only: :show

  resources :work_spaces do
    resources :bookings, only: [:index, :new, :create]
    collection do
      get "my_work_spaces", to: "work_spaces#my_work_spaces" # criar action my_work_spaces
    end
  end

  resources :bookings, only: %i[show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :work_space

  validates :start_date, :end_date, presence: true
  validate :amount_due
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :work_spaces

  has_one_attached :avatar

  validates :first_name, :last_name, :email, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work_space.rb
class WorkSpace < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :first_name, :last_name])
  end


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @work_space = WorkSpace.find(params[:work_space_id])
    @bookings = policy_scope(Booking).where(work_space: @work_space)
  end

  def show
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def new
    @work_space = WorkSpace.find(params[:work_space_id])
    @booking = Booking.new
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.work_space = WorkSpace.find(params[:work_space_id])

    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking), notice: "Booking was successfully created."
    else
      #resolver se o new é com aspas ou simbolo
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    set_booking
    authorize @booking
  end

  def update
    authorize @booking
    set_booking
    @booking.update(booking_params)

    if @booking.save
      redirect_to booking_path(@booking), notice: "Booking was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :amount_due)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.includes(avatar_attachment: :blob).all
  end

  def show
    @user = current_user
    authorize @user
  end

end

app/controllers/work_spaces_controller.rb
class WorkSpacesController < ApplicationController
  before_action :set_workspace, except: %i[index new create my_work_spaces]
  skip_before_action :authenticate_user!, only: [:index, :show]
  skip_after_action :verify_authorized, only: :my_work_spaces

  def index
    @work_spaces = policy_scope(WorkSpace)
    @markers = @work_spaces.geocoded.map do |work_space|
      {
        lat: work_space.latitude,
        lng: work_space.longitude
      }
    end
  end

  def my_work_spaces
    @work_spaces = policy_scope(WorkSpace).where(user: current_user)
  end

  def show
  end

  def new
    @work_space = WorkSpace.new
    authorize @work_space
  end

  def create
    @work_space = WorkSpace.new(work_space_params)
    @work_space.user = current_user
    authorize @work_space
    if @work_space.save
      redirect_to work_space_path(@work_space), notice: "Work Space was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @work_space.update(work_space_params)
    if @work_space.save
      redirect_to work_space_path(@work_space), notice: "Work Space was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @work_space.destroy
    redirect_to work_spaces_path, status: :see_other
  end

  private

  def work_space_params
    params.require(:work_space).permit(:user_id, :name, :price, :description, photos: [])
  end

  def set_workspace
    @work_space = WorkSpace.find(params[:id])
    authorize @work_space
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking.html.erb
<div id="<%= dom_id booking %>">
  <p>
    <strong>Start Date:</strong>
    <%= booking.start_date %>
  </p>

  <p>
    <strong>End Date:</strong>
    <%= booking.end_date %>
  </p>

</div>

app/views/bookings/_form.html.erb
<%= simple_form_for([@work_space, @booking]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%#= f.input :amount_due %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success" %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1>Bookings</h1>
<div>
  <ul>
    <% @bookings.each do |booking|%>
      <%= link_to booking do %>
        <li>
          <%= booking.start_date   %>
          <%= booking.end_date %>
          <%= booking.work_space.name %>
          <%= booking.amount_due %>
        </li>
      <%end%>
    <%end%>
  </ul>
  <div>
    <%= link_to "Create a new Booking", new_work_space_booking_path %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="row h-100 justify-content-center align-items-center mx-0">
  <div class="col-10 col-md-8 col-lg-6">
  <h1>New Booking</h1>

  <%= render "form", booking: @booking %>

  <div>
    <%= link_to "Back to work spaces", work_spaces_path, class: "btn btn-secondary" %>
  </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="booking-background-color">
<div class="booking-host">
  <h6>Your host is <%= @booking.work_space.user.first_name %></h6>
</div>
<div class="card-booking" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.coworkingbrasil.org/coworkingbrasi/wp-content/uploads/2019/06/1-salao-coworking.jpg?cx=center&cy=center&scale.option=fill&w=1200&cw=1200&h=628&ch=628)">


<div>
  <%= render @booking %>
</div>


</div>
  <div class="btn-show">
    <%= link_to "My bookings", user_path(current_user), class: "btn btn-secondary w-100" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path("logo_preto.png") %>

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />

  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/map" %> <%# n renderizar em todas as oags %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<p><%= current_user.email if current_user.present? %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links justify-content-center">

    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>

  </div>
  <div>
  <span class="footer-year">2022</span>
  <span class="footer-dot">·</span>
  <a href="/terms/privacy_policy" class="footer-text">Privacidade</a>
  <span class="footer-dot">·</span>
  <a href="/terms/privacy_policy" class="footer-text">Termos</a>
  <span class="footer-dot">·</span>
  <a href="/terms/privacy_policy" class="footer-text">Mapa do site</a>
  <span class="footer-dot">·</span>
  <a href="/terms/privacy_policy" class="footer-text">Informações da empresa</a>
  </div>
</div>

app/views/shared/_map.html.erb
<%# <div id='map' style='width: 400px; height: 300px;'></div> %>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoidGFrYXNoaW90YWthc2hpIiwiYSI6ImNsNmdyMnN1NzA2b3QzaW53NXJ2eXVsOHQifQ.meHbyd4MCtSuF4SsP6PYqA';
const map = new mapboxgl.Map({
    container: 'map', // container ID
    style: 'mapbox://styles/mapbox/streets-v11', // style URL
    center: [-74.5, 40], // starting position [lng, lat]
    zoom: 9, // starting zoom
    projection: 'globe' // display the map as a 3D globe
});
map.on('style.load', () => {
    map.setFog({}); // Set the default atmosphere style
});
</script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_preto_type.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">

            <% if current_user.avatar.present? %>
              <%= image_tag(current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag("https://res.cloudinary.com/dkearav60/image/upload/v1661462298/avatars/default_avatar_small_lkbynb.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <span class="dropdown-item" ><%= current_user.first_name if user_signed_in? %></span>

              <%= link_to "See my bookings", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Rent my work space", new_work_space_path, class: "dropdown-item" %>
              <%= link_to "View my work spaces", my_work_spaces_work_spaces_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h1 class="page-header pages">Your bookings</h1>
<div class="home-grid">
  <% @user.bookings.each do |booking|%>
    <div class="card-trip">
      <% if booking.work_space.photos.attached? %>
        <% booking.work_space.photos.each do |photo| %>
          <%= cl_image_tag photo.key, height: 200, width: 400 %>
        <% end %>
      <% else %>
        <%= image_tag "no_img.png" %>
      <% end %>

      <div class="card-trip-infos flex-column">
        <div>
          <strong>Name:</strong>
          <%= booking.work_space.name %>
        </div>
        <div>
          <strong>Price:</strong>
          <%= number_to_currency(booking.work_space.price) %>
        </div>
        <div>
          <strong>Description:</strong>
          <%= booking.work_space.description %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/work_spaces/_form.html.erb
<%= simple_form_for(@work_space) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success w-100" %>
  </div>
<% end %>

app/views/work_spaces/_work_space.html.erb
<div class="card">

  <% if work_space.photos.present? %>
    <%= cl_image_tag work_space.photos.first.key, height: 300, width: 400, crop: :fill %>
  <% else %>
    <%= image_tag "https://st.depositphotos.com/1008438/1896/i/950/depositphotos_18961721-stock-photo-office-work-place.jpg" %>
  <% end %>

  <div class="card-info">
    <div class='card-name'>
      <h2><%=work_space.name %></h2>
    </div>

    <div class='card-price'>
      <p>From <%= number_to_currency(work_space.price) %> per day</p>
    </div>

    <div class='card-host'>
      <p><i class="fa-solid fa-user"></i> Host: <%= work_space.user.first_name %></p>
    </div>

    <div class='button'>
      <%= link_to "View more", work_space, class: 'btn btn-dark my-3' %>
    </div>
  </div>
</div>

app/views/work_spaces/edit.html.erb
<h1>Edit work space</h1>
<%# pré-preencher o form com as informações do work_space a ser editado.%>

<%= render "form", work_space: @work_space %>

<div>
  <%= link_to "Back to work_spaces", work_spaces_path %>
</div>


<%# <%= f.select :cabinet_id, options_from_collection_for_select(Cabinet.order(:name).all, "id", "name", params[:cabinet_id]) %>

<%# <%= f.text_field :rfid, :value => params[:id] %>

app/views/work_spaces/index.html.erb
<div class="home-container">

  <div class='home-grid'>
    <%= render @work_spaces %>
  </div>

  <div id="map-container"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/work_spaces/my_work_spaces.html.erb
<h1>My workspaces</h1>
<div class='home-container'>
  <div class='no-map-home-grid'>

    <%= render @work_spaces %>

  </div>
</div>

app/views/work_spaces/new.html.erb
<div class="row h-100 justify-content-center align-items-center mx-0">
  <div class="col-10 col-md-8 col-lg-6">
  <h1>New work space</h1>

  <%= render "form", work_space: @work_space %>

  <div class="d-flex justify-content-center">
    <%= link_to "Back to work_spaces", work_spaces_path, class: "btn btn-secondary" %>
  </div>
  </div>
</div>

app/views/work_spaces/show.html.erb
<div class="card-trip">
<% if @work_space.photos.attached? %>
  <% @work_space.photos.each do |photo| %>
    <%= cl_image_tag photo.key, height: 200, width: 400 %>
  <% end %>
<% else %>
  <%= image_tag "no_img.png" %>
<% end %>

  <div id="ws-show">
    <div>
      <strong><%= @work_space.name %></strong>
    </div>
    <div>
      <%= number_to_currency(@work_space.price) %> per day.
    </div>
    <div>
      <%= @work_space.description %>
    </div>
  </div>
  <div class="btn-show">
    <%= link_to "Book this workspace", new_work_space_booking_path(@work_space), class: "btn btn-dark" %>

    <%= link_to "Back to workspaces", work_spaces_path, class: "btn btn-outline-secondary" %>
    <% if policy(@work_space).destroy? %>
      <%= link_to "Delete space", work_space_path(@work_space), data: { turbo_method: :delete }, class: "btn btn-danger text-white" %>
    <% end %>

  </div>
</div>